/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : FTM1_Config.h
**     Project     : zies
**     Processor   : MK22FN512VLH12
**     Component   : Init_FTM
**     Version     : Component 01.010, Driver 01.10, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-06-20, 16:05, # CodeGen: 1
**     Abstract    :
**          This file implements the FTM (FTM1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : M1_FTM1_QD1
**          Device                                         : FTM1
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Clock source                               : No clock
**              Prescaler                                  : divide by 1
**              Counter frequency                          : STOP
**              Counter init                               : 0
**              Modulo counter                             : 0xFFFF
**              Period                                     : Counter stopped
**              Deadtime                                   : 
**                Deadtime prescaler                       : divide by 1
**                Deadtime value                           : 0
**                Deadtime delay                           : DISABLED
**              Num of timer overflows                     : 0
**            FTM mode                                     : Enabled
**            BDM mode                                     : FTM counter stopped; channels outputs functional
**            Global time base                             : Disabled
**            Global time base output                      : Disabled
**            Write protection                             : Disabled
**            Quadrature decoder                           : 
**              Quadrature decoder                         : Enabled
**              Quadrature decoder mode                    : Phase A / Phase B
**              Phase A input polarity                     : Normal
**              Phase B input polarity                     : Normal
**              Phase A input filter                       : Disabled
**              Phase B input filter                       : Disabled
**            Combined channels                            : 
**              Channels 0 and 1                           : 
**                Complementary mode                       : Disabled
**                Fault control                            : Disabled
**                Synchronization                          : Disabled
**                Deadtime                                 : Disabled
**                Inverting                                : Disabled
**            Synchronization                              : 
**              Synchronization mode                       : Disabled
**                Counter reinitialization                 : Disabled
**              HW trigger mode                            : Enabled
**              CNTIN synchronization                      : Disabled
**              INVCTRL synchronization                    : Disabled
**              SWOCTRL synchronization                    : Disabled
**              Software Trigger                           : Disabled
**              OUTMASK synchronization                    : Disabled
**              Minimum loading point                      : Disabled
**              Maximum loading point                      : Disabled
**            External triggers                            : 
**              Counter init trigger                       : Disabled
**              Channel 0 trigger                          : Disabled
**              Channel 1 trigger                          : Disabled
**            Fault control settings                       : 
**              Fault control mode                         : Disabled
**              Fault input filter value                   : Disabled
**              Fault input 0 filter                       : Disabled
**              Fault input 0 polarity                     : High
**              Fault input 1 filter                       : Disabled
**              Fault input 1 polarity                     : High
**          Channels                                       : 
**            Channel 0                                    : Disabled
**            Channel 1                                    : Disabled
**          Pins                                           : 
**            Fault pins                                   : 
**              Fault pin 0                                : Disabled
**              Fault pin 1                                : Disabled
**            External clock pin                           : Disabled
**            Phase A Input pin                            : Disabled
**            Phase B Input pin                            : Disabled
**            HW Synchronization triggers                  : 
**              Hardware Trigger 0                         : Disabled
**              Hardware Trigger 1                         : Disabled
**              Hardware Trigger 2                         : Disabled
**          Interrupts                                     : 
**            Channels / Timer overflow / Fault            : 
**              Interrupt                                  : INT_FTM1
**              Interrupt request                          : Enabled
**              Interrupt priority                         : 128
**              ISR Name                                   : FTM1_ISR
**              Channels interrupt/DMA                     : See the respective Channel settings
**              Timer overflow interrupt                   : Enabled
**              Fault interrupt                            : Disabled
**          Initialization                                 : 
**            Initialize the Channels Output               : no
**            Load enable                                  : no
**            Channel 0 load select                        : no
**            Channel 1 load select                        : no
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void M1_FTM1_QD1_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FTM1_Config.h                                                  
** @version 01.10
** @brief
**          This file implements the FTM (FTM1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup FTM1_Config_module FTM1_Config module documentation
**  @{
*/         

#ifndef FTM1_Config_H_
#define FTM1_Config_H_

/* MODULE M1_FTM1_QD1. */



#define FTM1_MODE_VALUE_1 4
/* FTM1_MODE: FTMEN=1 */
#define FTM1_MODE_VALUE_2    0x01U
#define FTM1_MODE_MASK_2     0x01U
/* FTM1_COMBINE: FAULTEN0=0,SYNCEN0=0,DTEN0=0,COMP0=0 */
#define FTM1_COMBINE_VALUE   0x00U
#define FTM1_COMBINE_MASK    0x72U
/* FTM1_INVCTRL: INV0EN=0 */
#define FTM1_INVCTRL_VALUE   0x00U
#define FTM1_INVCTRL_MASK    0x01U
/* FTM1_C0SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0,ICRST=0 */
#define FTM1_C0SC_VALUE      0x00U
#define FTM1_C0SC_MASK       0xFFFFFFBEU
/* FTM1_C1SC: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CHF=0,MSB=0,MSA=0,ELSB=0,ELSA=0,ICRST=0 */
#define FTM1_C1SC_VALUE      0x00U
#define FTM1_C1SC_MASK       0xFFFFFFBEU
/* FTM1_OUTINIT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
#define FTM1_OUTINIT_VALUE   0x00U
#define FTM1_OUTINIT_MASK    0xFFFFFF00U
/* FTM1_FLTCTRL: FFVAL=0 */
#define FTM1_FLTCTRL_VALUE_1 0x00U
#define FTM1_FLTCTRL_MASK_1  0x0F00U
/* FTM1_FLTPOL: FLT1POL=0,FLT0POL=0 */
#define FTM1_FLTPOL_VALUE    0x00U
#define FTM1_FLTPOL_MASK     0x03U
/* FTM1_FLTCTRL: FFLTR1EN=0,FFLTR0EN=0,FAULT1EN=0,FAULT0EN=0 */
#define FTM1_FLTCTRL_VALUE_2 0x00U
#define FTM1_FLTCTRL_MASK_2  0x33U
/* FTM1_SYNC: SWSYNC=0,TRIG2=0,TRIG1=0,TRIG0=0,SYNCHOM=0,REINIT=0,CNTMAX=0,CNTMIN=0 */
#define FTM1_SYNC_VALUE      0x00U
#define FTM1_SYNC_MASK       0xFFU
/* FTM1_EXTTRIG: TRIGF=0,INITTRIGEN=0,CH1TRIG=0,CH0TRIG=0 */
#define FTM1_EXTTRIG_VALUE   0x00U
#define FTM1_EXTTRIG_MASK    0xF0U
/* FTM1_MOD: MOD=0xFFFF */
#define FTM1_MOD_VALUE       0xFFFFU
#define FTM1_MOD_MASK        0xFFFFU
/* FTM1_CNTIN: INIT=0 */
#define FTM1_CNTIN_VALUE     0x00U
#define FTM1_CNTIN_MASK      0xFFFFU
/* FTM1_DEADTIME: DTPS=0,DTVAL=0 */
#define FTM1_DEADTIME_VALUE  0x00U
#define FTM1_DEADTIME_MASK   0xFFU
/* FTM1_MODE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FAULTIE=0,FAULTM=0,PWMSYNC=0,INIT=0,FTMEN=1 */
#define FTM1_MODE_VALUE_3    0x01U
#define FTM1_MODE_MASK_3     0xFFFFFFEBU
/* FTM1_SYNCONF: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SYNCMODE=0,??=0,SWOC=0,INVC=0,??=0,CNTINC=0,??=0,HWTRIGMODE=0 */
#define FTM1_SYNCONF_VALUE   0x00U
#define FTM1_SYNCONF_MASK    0xFFE0E0FFU
/* FTM1_SC: TOF=0,TOIE=1,CLKS=0,PS=0 */
#define FTM1_SC_VALUE_3      0x40U
#define FTM1_SC_MASK_3       0xDFU
/* FTM1_FMS: FAULTF=0,WPEN=0,FAULTF3=0,FAULTF2=0,FAULTF1=0,FAULTF0=0 */
#define FTM1_FMS_VALUE       0x00U
#define FTM1_FMS_MASK        0xCFU
/* FTM1_QDCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,PHAFLTREN=0,PHBFLTREN=0,PHAPOL=0,PHBPOL=0,QUADMODE=0,QUADIR=0,TOFDIR=0,QUADEN=1 */
#define FTM1_QDCTRL_VALUE    0x01U
/* FTM1_CONF: GTBEOUT=0,GTBEEN=0,BDMMODE=0,NUMTOF=0 */
#define FTM1_CONF_VALUE      0x00U
#define FTM1_CONF_MASK       0x06DFU
/* FTM1_PWMLOAD: LDOK=0,CH1SEL=0,CH0SEL=0 */
#define FTM1_PWMLOAD_VALUE   0x00U
#define FTM1_PWMLOAD_MASK    0x0203U

#define FTM1_AUTOINIT

#define INT_FTM1_ISR FTM1_ISR

/* END M1_FTM1_QD1. */
#endif /* #ifndef __FTM1_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
